apiVersion: v1
kind: Pod
metadata:
  name: first-pod-on-my-mac
  labels:
    app: myapp
    type: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        
      